package nl.rhaydus.nestbox.core.presentation.theme

import androidx.compose.ui.graphics.Color

// Paper / ink / rust (design system §A1). Named tokens map onto Material roles per §A1's mapping
// guidance: canvas -> background/surface, reader canvas -> surfaceBright, card -> surfaceContainerLow,
// inline-code wash -> surfaceContainerHigh, ink -> onSurface, body -> onSurfaceVariant, meta -> outline,
// hairline -> outlineVariant, accent -> primary, positive -> tertiary, ink cards -> inverseSurface /
// inverseOnSurface. Slots the redline sheet doesn't pin (the tonal containers Material still expects)
// are derived warm-neutral / warm-rust tints, kept close in hue to the named tokens.
val primaryLight = Color(0xFFBC4A20)
val onPrimaryLight = Color(0xFFF5EFE2)
val primaryContainerLight = Color(0xFFF6DBC9)
val onPrimaryContainerLight = Color(0xFF6B2A12)
val secondaryLight = Color(0xFF6B655A)
val onSecondaryLight = Color(0xFFF5EFE2)
val secondaryContainerLight = Color(0xFFEFE6D4)
val onSecondaryContainerLight = Color(0xFF3A362C)
val tertiaryLight = Color(0xFF3E7C4F)
val onTertiaryLight = Color(0xFFF5EFE2)
val tertiaryContainerLight = Color(0xFFD9EDD9)
val onTertiaryContainerLight = Color(0xFF1F4A2A)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF5EFE2)
val onBackgroundLight = Color(0xFF23201A)
val surfaceLight = Color(0xFFF5EFE2)
val onSurfaceLight = Color(0xFF23201A)
val surfaceVariantLight = Color(0xFFE4DCC8)
val onSurfaceVariantLight = Color(0xFF33302A)
val outlineLight = Color(0xFF99917C)
val outlineVariantLight = Color(0xFFE4DCC8)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF23201A)
val inverseOnSurfaceLight = Color(0xFFF5EFE2)
val inversePrimaryLight = Color(0xFFE8896A)
val surfaceDimLight = Color(0xFFE5DCC5)
val surfaceBrightLight = Color(0xFFF9F4E9)
val surfaceContainerLowestLight = Color(0xFFFFFDF7)
val surfaceContainerLowLight = Color(0xFFFCF8EE)
val surfaceContainerLight = Color(0xFFF5EEDC)
val surfaceContainerHighLight = Color(0xFFEFE7D4)
val surfaceContainerHighestLight = Color(0xFFE9E0CB)

// Dusk mode (design system §E1). Warm dark, never neutral grey: body and ink invert to light warm
// tones, meta stays roughly flat (it is read against both canvases), the accent lifts for contrast,
// and ink cards / the floating tab bar deliberately keep their light-mode ink value (§E1 "toolbar
// unchanged"), which is why inverseSurface/inverseOnSurface hold constant across both schemes below.
val primaryDark = Color(0xFFE06A3C)
val onPrimaryDark = Color(0xFF2B1108)
val primaryContainerDark = Color(0xFF6B2A12)
val onPrimaryContainerDark = Color(0xFFFFD9C4)
val secondaryDark = Color(0xFFB3AA93)
val onSecondaryDark = Color(0xFF23201A)
val secondaryContainerDark = Color(0xFF3A342A)
val onSecondaryContainerDark = Color(0xFFE8DFC9)
val tertiaryDark = Color(0xFF6FA97F)
val onTertiaryDark = Color(0xFF0F2A16)
val tertiaryContainerDark = Color(0xFF2A4A32)
val onTertiaryContainerDark = Color(0xFFC8EAD0)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF191612)
val onBackgroundDark = Color(0xFFEDE6D2)
val surfaceDark = Color(0xFF191612)
val onSurfaceDark = Color(0xFFEDE6D2)
val surfaceVariantDark = Color(0xFF2E2920)
val onSurfaceVariantDark = Color(0xFFCFC6B0)
val outlineDark = Color(0xFF8F866F)
val outlineVariantDark = Color(0xFF2E2920)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFF23201A)
val inverseOnSurfaceDark = Color(0xFFF5EFE2)
val inversePrimaryDark = Color(0xFFBC4A20)
val surfaceDimDark = Color(0xFF191612)
val surfaceBrightDark = Color(0xFF1C1815)
val surfaceContainerLowestDark = Color(0xFF100D0A)
val surfaceContainerLowDark = Color(0xFF1E1A15)
val surfaceContainerDark = Color(0xFF211D17)
val surfaceContainerHighDark = Color(0xFF2E2920)
val surfaceContainerHighestDark = Color(0xFF362F25)
